# Generated by Django 3.0.6 on 2020-05-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beverage',
            old_name='name',
            new_name='Beverage_text',
        ),
    ]
