# Generated by Django 3.0.6 on 2020-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
